// <auto-generated />
namespace Veterinaria.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateOwner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateOwner));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271921176_update-Owner"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
